coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 70%
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/"
  - "**/*.test.js"
  - "**/*.spec.js"
  - "coverage/"
  - "node_modules/"
  - ".github/"
  - "docs/"
  - "*.md" 